version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: cv_project_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cv_project
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d cv_project"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: