[project]
name = "segmentation"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.7",
    "numpy>=2.2.6",
    "opencv-python>=4.12.0.88",
]

[dependency-groups]
dev = [
    "ipykernel>=6.30.1",
]
